[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = admin2026
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo2026
db_maxconn = 64
proxy_mode = False
without_demo = False
workers = 0
max_cron_threads = 1
log_level = info
log_handler = :INFO
list_db = True